import os
import secrets
from flask import Flask, redirect, url_for
from flask_login import LoginManager
from models import db, User
from seed import seed_database

DATA_DIR = os.environ.get("DATA_DIR", "/app/data")
SERVER_DATA_DIR = os.environ.get("SERVER_DATA_DIR", "/app/server/data")


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = _get_or_create_secret_key()
    app.config["SQLALCHEMY_DATABASE_URI"] = f"sqlite:///{DATA_DIR}/custom_server.db"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)

    login_manager = LoginManager(app)
    login_manager.login_view = "auth.login"
    login_manager.login_message = "Please log in to access this page."

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    with app.app_context():
        db.create_all()
        seed_database()
        _write_server_config()

    from routes.auth import auth_bp
    from routes.dashboard import dashboard_bp
    from routes.agents import agents_bp
    from routes.devices import devices_bp
    from routes.plugins import plugins_bp
    from routes.settings import settings_bp
    from routes.api import api_bp

    app.register_blueprint(auth_bp)
    app.register_blueprint(dashboard_bp)
    app.register_blueprint(agents_bp, url_prefix="/agents")
    app.register_blueprint(devices_bp, url_prefix="/devices")
    app.register_blueprint(plugins_bp, url_prefix="/plugins")
    app.register_blueprint(settings_bp, url_prefix="/settings")
    app.register_blueprint(api_bp)  # /config/* and /agent/* — no prefix

    @app.route("/")
    def index():
        return redirect(url_for("dashboard.index"))

    return app


def _get_or_create_secret_key():
    key_file = os.path.join(DATA_DIR, ".flask_secret")
    os.makedirs(DATA_DIR, exist_ok=True)
    if os.path.exists(key_file):
        with open(key_file) as f:
            return f.read().strip()
    key = secrets.token_hex(32)
    with open(key_file, "w") as f:
        f.write(key)
    return key


def _get_or_create_api_secret():
    secret_file = os.path.join(DATA_DIR, ".api_secret")
    if os.path.exists(secret_file):
        with open(secret_file) as f:
            return f.read().strip()
    secret = secrets.token_hex(24)
    with open(secret_file, "w") as f:
        f.write(secret)
    return secret


def _write_server_config():
    """Write data/.config.yaml for xiaozhi-server to connect to this Flask API."""
    os.makedirs(SERVER_DATA_DIR, exist_ok=True)
    config_path = os.path.join(SERVER_DATA_DIR, ".config.yaml")

    api_secret = _get_or_create_api_secret()
    flask_port = int(os.environ.get("FLASK_PORT", 5001))
    ws_host = os.environ.get("SERVER_HOST", "YOUR_HOST_IP")
    ws_port = int(os.environ.get("WS_PORT", 8000))
    http_port = int(os.environ.get("HTTP_PORT", 8003))

    content = f"""# Auto-generated by custom-server web app — do not edit manually.
# Change settings via the web UI at http://localhost:{flask_port}

manager-api:
  url: http://localhost:{flask_port}
  secret: {api_secret}
  max_retries: 3
  retry_delay: 5

server:
  ip: 0.0.0.0
  port: {ws_port}
  http_port: {http_port}
  websocket: ws://{ws_host}:{ws_port}/xiaozhi/v1/
  vision_explain: http://{ws_host}:{http_port}/mcp/vision/explain
  auth:
    enabled: false
"""
    with open(config_path, "w") as f:
        f.write(content)


if __name__ == "__main__":
    app = create_app()
    port = int(os.environ.get("FLASK_PORT", 5001))
    app.run(host="0.0.0.0", port=port, debug=False)
